# Generated by Django 3.0 on 2020-11-27 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='не определено', max_length=128, verbose_name='Заголовок')),
                ('create', models.DateField(default=datetime.date.today, verbose_name='Дата добавления')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('short_description', models.TextField(verbose_name='Короткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('author', models.CharField(default='не определено', max_length=64, verbose_name='Автор')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
