# Generated by Django 3.1.2 on 2020-11-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201129_2314'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='full_description',
            new_name='description_full',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='short_description',
            new_name='description_short',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='home.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='home.subcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='article', to='home.Tags'),
        ),
    ]
