# Generated by Django 3.1.2 on 2020-11-29 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='не определено', max_length=50, verbose_name='Название')),
                ('progress', models.CharField(default='', max_length=255, verbose_name='Прогрес выполнения')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('dataTime', models.DateField(default=datetime.date.today, verbose_name='Дата добавления')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Задачу',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
