# Generated by Django 3.1.2 on 2020-11-29 23:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='не определено', max_length=50, verbose_name='Название')),
                ('progress', models.CharField(default='', max_length=255, verbose_name='Прогрес выполнения')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('description_full', models.TextField(verbose_name='Полное описание')),
                ('create', models.DateField(default=datetime.date.today, verbose_name='Дата добавления')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.subcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='home.Tags')),
            ],
            options={
                'verbose_name': 'Задачу',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
