# Generated by Django 3.1.2 on 2020-11-29 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201129_2314'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='dataTime',
            new_name='create',
        ),
        migrations.AddField(
            model_name='tasks',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.subcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='home.Tags'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
    ]
