# Generated by Django 3.1.2 on 2020-11-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201130_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='tasks',
            name='description_full',
            field=models.TextField(default=1, verbose_name='Полное описание'),
            preserve_default=False,
        ),
    ]
