# Generated by Django 3.1.2 on 2020-11-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='titleTags',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='slugTags',
            new_name='slug',
        ),
    ]
