# Generated by Django 3.0 on 2020-11-27 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название проекта')),
                ('type', models.CharField(default='не определено', max_length=64, verbose_name='Раздел')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('progress', models.CharField(default='', max_length=255, verbose_name='Прогрес выполнения')),
                ('create', models.DateField(default=datetime.date.today, verbose_name='Дата добавления')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('short_description', models.TextField(max_length=96, verbose_name='Короткое описание проекта')),
                ('full_description', models.TextField(verbose_name='Полное описание проекта')),
                ('author', models.CharField(max_length=64, verbose_name='Автор проекта')),
                ('thumbnail', models.ImageField(blank=True, default='null.jpg', upload_to='project/%Y/%m/%d', verbose_name='Эскиз')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
