# Generated by Django 3.1.2 on 2020-11-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='subcategory',
            new_name='category_sub',
        ),
    ]
