# Generated by Django 3.1.2 on 2020-11-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201129_2314'),
        ('projects', '0002_auto_20201129_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='home.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description_full',
            field=models.TextField(default=1, verbose_name='Полное описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description_short',
            field=models.TextField(default=1, verbose_name='Короткое описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='home.subcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='project', to='home.Tags'),
        ),
    ]
