# Generated by Django 3.1.2 on 2020-11-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201130_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=14, verbose_name='Название проекта'),
        ),
    ]
