# Generated by Django 3.1.2 on 2020-11-29 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('author', models.CharField(max_length=64, verbose_name='Кто принёс')),
                ('thumbnail', models.ImageField(blank=True, default='null.jpg', upload_to='warehouse/%Y/%m/%d', verbose_name='Фото')),
                ('description_full', models.TextField(verbose_name='Описание')),
                ('number', models.IntegerField(verbose_name='Колличество')),
                ('create', models.DateField(default=datetime.date.today, verbose_name='Дата добавления')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Что-то',
                'verbose_name_plural': 'Что-ты',
            },
        ),
    ]
